### PR TITLE
Adding x64 build of the dfsc codec

### PR DESCRIPTION
**Pull request by tmp170422**
Tested it and it works for me.
Unable to fix the installation scripts by myself.
Please help.

### CODE REVIEW

**Comment by daxingplay** [comment]
Looking forward to be merged

**Comment by tmp170422** [comment]
> 
> Looking forward to be merged, can it be used in modern Premiere like Premiere CC 2018?

Can't say anything about Premiere. Still using it though with MAGIX Vegas Pro 16 (2 months old) on windows 7.
People said there were problems with Windows 10, which I don't have and cannot test as well.

**Comment by satishsampath** [comment]
tmp170422 - I'm starting to merge this pull request. Can you give me steps
to test this change and in which video editor to test?

**Comment by tmp170422** [comment]
> tmp170422 - I'm starting to merge this pull request. Can you give me steps to test this change and in which video editor to test?

I tested it only in Sony Vegas Pro 13 and MAGIX Vegas Pro 15 and 16 and only on Windows 7. Still works for me. The steps were, build the codecs and enter them manually in the Windows registry.

I am also using Premiere CC Pro 2019 with a frame server, but it changed a lot in the program dir layout, so I had to go with another solution at https://sourceforge.net/projects/advancedfs/, and it worked. That thing, however, did not support Vegas.

**Comment by wwaag76** [comment]
Can you make sure to test on a Win10 system?  For me, it works OK on Win7 but not Win10.  Thanks.

**Comment by satishsampath** [comment]
@tmp170422  does Premiere Pro CC come with any built-in frameserving capabilities, or do you need an external frameserver like the one you used? If it's external only, I can update debugmode frameserver to work with Premiere Pro CC & Elements too.

**Comment by tmp170422** [comment]
> @tmp170422 does Premiere Pro CC come with any built-in frameserving capabilities, or do you need an external frameserver like the one you used? If it's external only, I can update debugmode frameserver to work with Premiere Pro CC & Elements too.

I have never used the codecs that come with Premiere, I only use external frameserver with ffmpeg command line. That would be great if Debugmode could support the latest Premiere. I believe many folks here would be happy.

**Comment by satishsampath** [comment]
@tmp170422 did you get a 64 bit version of the windows DDK for msacmdrv.h ? Looks like the one in the github repo is the 32 bit version, hence padsi->dwDriver is a DWORD instead of DWORD_PTR.

**Comment by tmp170422** [comment]
> @tmp170422 did you get a 64 bit version of the windows DDK for msacmdrv.h ? Looks like the one in the github repo is the 32 bit version, hence padsi->dwDriver is a DWORD instead of DWORD_PTR.

Mine was from Visual Studio 2017:
`
typedef struct tACMDRVSTREAMINSTANCE
{
    DWORD               cbStruct;
    LPWAVEFORMATEX      pwfxSrc;
    LPWAVEFORMATEX      pwfxDst;
    LPWAVEFILTER        pwfltr;
    DWORD_PTR           dwCallback;
    DWORD_PTR           dwInstance;
    DWORD               fdwOpen;
    DWORD               fdwDriver;
    DWORD_PTR           dwDriver;
    HACMSTREAM          has;

} ACMDRVSTREAMINSTANCE, *PACMDRVSTREAMINSTANCE, FAR *LPACMDRVSTREAMINSTANCE;
`

**Comment by satishsampath** [comment]
Thanks, @tmp170422 . I can build and install now. It's serving properly from Vegas Pro 16 and opening fine in VirtualDub. However I can't open the signpost AVI file in windows media player or in VLC. Looks like the audio/video driver registration process is likely different/needs more steps.
Which applications did you test with for opening the signpost AVI file? Are you able to playback the signpost in any media player?

**Comment by wwaag76** [comment]
If I might add something.  My concern is rendering from Vegas into Avisynth and then into 64bit FFmpeg.  What I found is that the build produced by tmp170422 worked OK in Win7.  However, in Win10, it failed,  forcing me to use avs2pipemod in order to open Avisynth in FFmpeg.

Here is a typical Avisynth script that I use.  Line 3 is the frameserver input.
```
SetMemoryMax(2048)
SetFilterMTMode("DEFAULT_MT_MODE", 2)
AVISource("C:\ProgramData\HappyOtterScripts\Magix Vegas Pro\RenderPlus\fs_18852.avi").killAudio()
ConvertToYV12(interlaced=false,matrix="PC.709")
AssumeFPS (30000,1001)
Prefetch(8)
```
And here is a typical commandline:

`avs2pipemod -y4mp "C:\ProgramData\HappyOtterScripts\Magix Vegas Pro\RenderPlus\RenderPlus.avs"  | ffmpeg -y -f yuv4mpegpipe -i -  -itsoffset 0.0444 -i "C:\ProgramData\HappyOtterScripts\Magix Vegas Pro\RenderPlus\wav_18852.wav" -map 0:0 -map 1:0  -c:v libx264  -pix_fmt yuv420p -crf 18 -preset slower -c:a aac -b:a 320k  "C:\Temp\Sergio 2 version 21 selection for upload-07.mp4"`

In Win7 I can open the Avisynth file directly in FFmpeg, but not in Win10.

**Comment by tmp170422** [comment]
For me it worked with MPC-HC x64 player, though there were some problems with sound and playback from random position. PCM instead of ACM option did more stable. It worked also with most anything via an avisynth file.

Here is how I registered it (I added 32/64 dll suffixes, though it should work without them):
`
REGEDIT4

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Drivers32]
"vidc.dfsc"="dfsc64.dll"
"msacm.dfscacm"="dfscacm64.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\drivers.desc]
"dfsc64.dll"="DebugMode FSVFWC (internal use)"
"dfscacm64.dll"="DebugMode FSACMC (internal use)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Drivers32]
"vidc.dfsc"="dfsc32.dll"
"msacm.dfscacm"="dfscacm32.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\drivers.desc]
"dfsc32.dll"="DebugMode FSVFWC (internal use)"
"dfscacm32.dll"="DebugMode FSACMC (internal use)"
`

**Comment by satishsampath** [comment]
Thanks, both.
@tmp170422  I verified that my local build indeed works with MPC-HC. Can you try with VLC or Windows Media Player and let me know if they work for you? I'd like to get it working with all players/decoders before releasing (and fix the windows 10 issue too).

**Comment by tmp170422** [comment]
> @tmp170422 I verified that my local build indeed works with MPC-HC. Can you try with VLC or Windows Media Player and let me know if they work for you? I'd like to get it working with all players/decoders before releasing (and fix the windows 10 issue too).

I think those players just can't be made working with the dfsc codec as they somehow bypass the codecs mechanism by making assumptions about avi file length and contents.

**Comment by satishsampath** [comment]
@tmp170422 @daxingplay @wwaag76 I have an installer tested on Win7 64bit with Vegas 16 pro. Can I request your help in trying it out? I'd like to verify if it works on Vegas, Premiere and on Windows 10 before releasing. You can email me at 'satish -at- debugmode.com' and I'll send the build/exe for testing.

**Comment by satishsampath** [comment]
This has been added to the v3.0 release, so closing this pull request.

**Pull request closed without merging**
